export const STORAGE_KEYS = {
  usuarios: "usuarios_gs",
  clientes: "clientes_gs",
  deudores: "deudores_gs",
  productos: "productos_gs",
  ventas: "ventas",
  egresos: "egresos_gs",
  session: "session_gs",
  theme: "theme",
  userPhoto: "userPhoto",
  perfil: "config_perfil",
  sistema: "config_sistema",
  tienda: "config_tienda",
  tiendaLogo: "tienda_logo",
};
